default: &default
  adapter: postgresql
  database: 'sabotage_blog'
  username: 'sabotage'
  password: '123'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
 
test:
  <<: *default
  database: 'sabotage_blog_test'

production:
  <<: *default
  database: 'sabotage_blog_production'
